/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: q99j7awHXXkWnTbGHfeoZt

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariants_3ItArvxMaTek } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 3ITArvxMaTEK/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariants_3ItArvxMaTek
});
