/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: q99j7awHXXkWnTbGHfeoZt
// Component: ZScbKbJPAq6N

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Header from "../../Header"; // plasmic-import: fvrrAjoqQjp-/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: q99j7awHXXkWnTbGHfeoZt/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: q99j7awHXXkWnTbGHfeoZt/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: q99j7awHXXkWnTbGHfeoZt/projectcss
import sty from "./PlasmicHome.module.css"; // plasmic-import: ZScbKbJPAq6N/css

import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: dgb4cKOaBpT2/icon
import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: AkT3y3h5ln-C/icon
import Icon7Icon from "./icons/PlasmicIcon__Icon7"; // plasmic-import: -6EMW7tAnRc4/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: vJ8Yo6oAcXXo/icon
import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: 2mcOfPkf23U6/icon
import Icon10Icon from "./icons/PlasmicIcon__Icon10"; // plasmic-import: 5UiK3G_OqHQg/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: JRxYeOBgIVu_/icon
import Icon9Icon from "./icons/PlasmicIcon__Icon9"; // plasmic-import: JgAWzmHnyCvd/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: rKzojCvLNCrI/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicHome__VariantMembers = {};
export type PlasmicHome__VariantsArgs = {};
type VariantPropType = keyof PlasmicHome__VariantsArgs;
export const PlasmicHome__VariantProps = new Array<VariantPropType>();

export type PlasmicHome__ArgsType = {};
type ArgPropType = keyof PlasmicHome__ArgsType;
export const PlasmicHome__ArgProps = new Array<ArgPropType>();

export type PlasmicHome__OverridesType = {
  root?: Flex__<"div">;
  nav?: Flex__<"nav">;
  h1?: Flex__<"h1">;
  footer?: Flex__<"footer">;
};

export interface DefaultHomeProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHome__RenderFunc(props: {
  variants: PlasmicHome__VariantsArgs;
  args: PlasmicHome__ArgsType;
  overrides: PlasmicHome__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <Header className={classNames("__wab_instance", sty.header__cbJUt)} />

          <div className={classNames(projectcss.all, sty.freeBox__aejQc)}>
            <header className={classNames(projectcss.all, sty.header__db0Qt)}>
              <div className={classNames(projectcss.all, sty.freeBox__oe94V)}>
                <nav
                  data-plasmic-name={"nav"}
                  data-plasmic-override={overrides.nav}
                  className={classNames(projectcss.all, sty.nav)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__vqafO)}
                  >
                    <span
                      className={classNames(
                        projectcss.all,
                        projectcss.span,
                        projectcss.span__q99j7,
                        projectcss.__wab_text,
                        sty.span__mzymz
                      )}
                    >
                      {"Silkroad Fellowship"}
                    </span>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__pLumv)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__m8SEh)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.a__q99j7,
                          sty.link__ecyGj
                        )}
                        component={Link}
                        legacyBehavior={false}
                        platform={"nextjs"}
                      >
                        <span
                          className={classNames(
                            projectcss.all,
                            projectcss.span,
                            projectcss.span__q99j7,
                            projectcss.__wab_text,
                            sty.span__nheD9
                          )}
                        >
                          {"Program"}
                        </span>
                      </PlasmicLink__>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__djCsm)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.a__q99j7,
                          sty.link__rlbBl
                        )}
                        component={Link}
                        legacyBehavior={false}
                        platform={"nextjs"}
                      >
                        <span
                          className={classNames(
                            projectcss.all,
                            projectcss.span,
                            projectcss.span__q99j7,
                            projectcss.__wab_text,
                            sty.span__cphHp
                          )}
                        >
                          {"Benefits"}
                        </span>
                      </PlasmicLink__>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__fgCd4)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.a__q99j7,
                          sty.link__klCiX
                        )}
                        component={Link}
                        legacyBehavior={false}
                        platform={"nextjs"}
                      >
                        <span
                          className={classNames(
                            projectcss.all,
                            projectcss.span,
                            projectcss.span__q99j7,
                            projectcss.__wab_text,
                            sty.span__kIMeq
                          )}
                        >
                          {"Timeline"}
                        </span>
                      </PlasmicLink__>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__qbRcQ)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.a__q99j7,
                          sty.link__t1IQl
                        )}
                        component={Link}
                        legacyBehavior={false}
                        platform={"nextjs"}
                      >
                        <span
                          className={classNames(
                            projectcss.all,
                            projectcss.span,
                            projectcss.span__q99j7,
                            projectcss.__wab_text,
                            sty.span__v6XpM
                          )}
                        >
                          {"Apply"}
                        </span>
                      </PlasmicLink__>
                    </div>
                  </div>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.a__q99j7,
                      sty.link__hPkFz
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    <span
                      className={classNames(
                        projectcss.all,
                        projectcss.span,
                        projectcss.span__q99j7,
                        projectcss.__wab_text,
                        sty.span__jo4Ql
                      )}
                    >
                      {"Apply Now"}
                    </span>
                  </PlasmicLink__>
                </nav>
              </div>
            </header>
            <section
              className={classNames(projectcss.all, sty.section___3MJi6)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__mvh9H)}>
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.h1__q99j7,
                    projectcss.__wab_text,
                    sty.h1
                  )}
                >
                  {"Silkroad Fellowship Program"}
                </h1>
                <p
                  className={classNames(
                    projectcss.all,
                    projectcss.p,
                    projectcss.p__q99j7,
                    projectcss.__wab_text,
                    sty.p__uftf9
                  )}
                >
                  {
                    "6-week intensive program in Silicon Valley \u2022 July - August 2024 \u2022 Full immersion in startup ecosystem with housing, meals, and stipend included"
                  }
                </p>
                <div className={classNames(projectcss.all, sty.freeBox__xc2SZ)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.a__q99j7,
                      sty.link___0Xu4J
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    <span
                      className={classNames(
                        projectcss.all,
                        projectcss.span,
                        projectcss.span__q99j7,
                        projectcss.__wab_text,
                        sty.span__t3Wvl
                      )}
                    >
                      {"Apply Now"}
                    </span>
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.a__q99j7,
                      sty.link___1K4Ep
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    <span
                      className={classNames(
                        projectcss.all,
                        projectcss.span,
                        projectcss.span__q99j7,
                        projectcss.__wab_text,
                        sty.span__chP5P
                      )}
                    >
                      {"Learn More"}
                    </span>
                  </PlasmicLink__>
                </div>
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__eRyJe)}>
              <div className={classNames(projectcss.all, sty.freeBox__k5Uhb)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.h2__q99j7,
                    projectcss.__wab_text,
                    sty.h2___9HsN9
                  )}
                >
                  {"Transform Your Future in Silicon Valley"}
                </h2>
                <div className={classNames(projectcss.all, sty.freeBox__cCkgy)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__sQhp4)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__h1Ho9)}
                    >
                      <Icon4Icon
                        className={classNames(projectcss.all, sty.svg__vBxOw)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.h3__q99j7,
                        projectcss.__wab_text,
                        sty.h3__o0VcB
                      )}
                    >
                      {"6-Week Intensive"}
                    </h3>
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.p__q99j7,
                        projectcss.__wab_text,
                        sty.p__vq1Z7
                      )}
                    >
                      {
                        "Comprehensive program running from July to August, designed to accelerate your entrepreneurial journey in the heart of Silicon Valley."
                      }
                    </p>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__pbqLh)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__eWiqG)}
                    >
                      <Icon8Icon
                        className={classNames(projectcss.all, sty.svg___0MYz)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.h3__q99j7,
                        projectcss.__wab_text,
                        sty.h3__fNJtR
                      )}
                    >
                      {"Full Support"}
                    </h3>
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.p__q99j7,
                        projectcss.__wab_text,
                        sty.p__byOr
                      )}
                    >
                      {
                        "Complete package including housing, daily lunch, stipend, and mentorship from Silicon Valley veterans and successful entrepreneurs."
                      }
                    </p>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__shEIc)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__pRqu)}
                    >
                      <Icon7Icon
                        className={classNames(projectcss.all, sty.svg__hptZ)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.h3__q99j7,
                        projectcss.__wab_text,
                        sty.h3__v55Jo
                      )}
                    >
                      {"Silicon Valley Immersion"}
                    </h3>
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.p__q99j7,
                        projectcss.__wab_text,
                        sty.p__sZfBt
                      )}
                    >
                      {
                        "Direct access to the startup ecosystem, networking events, company visits, and connections with top-tier investors and founders."
                      }
                    </p>
                  </div>
                </div>
              </div>
            </section>
            <section
              className={classNames(projectcss.all, sty.section___785Nc)}
            >
              <div className={classNames(projectcss.all, sty.freeBox___2Kffr)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.h2__q99j7,
                    projectcss.__wab_text,
                    sty.h2__mgXv
                  )}
                >
                  {"What We Provide"}
                </h2>
                <div className={classNames(projectcss.all, sty.freeBox__pIa4W)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__dg5Ce)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__qiRKp)}
                    >
                      <Icon5Icon
                        className={classNames(projectcss.all, sty.svg__neQk)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.h3__q99j7,
                        projectcss.__wab_text,
                        sty.h3___93TS
                      )}
                    >
                      {"Housing"}
                    </h3>
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.p__q99j7,
                        projectcss.__wab_text,
                        sty.p___1XWmo
                      )}
                    >
                      {
                        "Fully furnished accommodation in premium locations close to major tech companies and startup hubs."
                      }
                    </p>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__zj4B2)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__bjNmJ)}
                    >
                      <Icon6Icon
                        className={classNames(projectcss.all, sty.svg__j64Z)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.h3__q99j7,
                        projectcss.__wab_text,
                        sty.h3___4Grr
                      )}
                    >
                      {"Daily Lunch"}
                    </h3>
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.p__q99j7,
                        projectcss.__wab_text,
                        sty.p__uhQ
                      )}
                    >
                      {
                        "Nutritious lunch provided every day, allowing you to focus on learning and networking without meal planning."
                      }
                    </p>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mdBdi)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__z74E)}
                    >
                      <Icon10Icon
                        className={classNames(projectcss.all, sty.svg___26SrH)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.h3__q99j7,
                        projectcss.__wab_text,
                        sty.h3__zlwkb
                      )}
                    >
                      {"Stipend"}
                    </h3>
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.p__q99j7,
                        projectcss.__wab_text,
                        sty.p__oK2B
                      )}
                    >
                      {
                        "Financial support to cover your living expenses, allowing you to focus entirely on the program experience."
                      }
                    </p>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__eZCs6)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__qau8W)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg___9U49P)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.h3__q99j7,
                        projectcss.__wab_text,
                        sty.h3__vlqab
                      )}
                    >
                      {"Mentorship"}
                    </h3>
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.p__q99j7,
                        projectcss.__wab_text,
                        sty.p__ptov1
                      )}
                    >
                      {
                        "One-on-one guidance from successful entrepreneurs, VCs, and industry leaders throughout the program."
                      }
                    </p>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__pHbZ7)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__mfIjR)}
                    >
                      <Icon9Icon
                        className={classNames(projectcss.all, sty.svg__kZgx6)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.h3__q99j7,
                        projectcss.__wab_text,
                        sty.h3__gYLf
                      )}
                    >
                      {"Network Access"}
                    </h3>
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.p__q99j7,
                        projectcss.__wab_text,
                        sty.p__rcwGm
                      )}
                    >
                      {
                        "Exclusive access to Silicon Valley's startup ecosystem, including investor meetings and company visits."
                      }
                    </p>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__zv2Ab)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__zkHal)}
                    >
                      <Icon2Icon
                        className={classNames(projectcss.all, sty.svg__xfHoY)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.h3__q99j7,
                        projectcss.__wab_text,
                        sty.h3__rtUyR
                      )}
                    >
                      {"Workshops & Events"}
                    </h3>
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.p__q99j7,
                        projectcss.__wab_text,
                        sty.p__ztWKl
                      )}
                    >
                      {
                        "Intensive workshops on fundraising, product development, marketing, and scaling your startup."
                      }
                    </p>
                  </div>
                </div>
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__apeu)}>
              <div className={classNames(projectcss.all, sty.freeBox__dLcwO)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.h2__q99j7,
                    projectcss.__wab_text,
                    sty.h2__nHzTp
                  )}
                >
                  {"Program Timeline"}
                </h2>
                <div className={classNames(projectcss.all, sty.freeBox__yPw1)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__fhaPh)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.h3__q99j7,
                        projectcss.__wab_text,
                        sty.h3__axt93
                      )}
                    >
                      {"Application Deadline - June 1st, 2024"}
                    </h3>
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.p__q99j7,
                        projectcss.__wab_text,
                        sty.p__h4GK
                      )}
                    >
                      {
                        "Submit your application with all required documents. Late applications will not be considered. Don't miss this opportunity!"
                      }
                    </p>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__wxDcm)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.h3__q99j7,
                        projectcss.__wab_text,
                        sty.h3__maS2V
                      )}
                    >
                      {"Selection Process - June 2024"}
                    </h3>
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.p__q99j7,
                        projectcss.__wab_text,
                        sty.p__iCw7
                      )}
                    >
                      {
                        "Review of applications, interviews with shortlisted candidates, and final selection announcements by mid-June."
                      }
                    </p>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__l9OdA)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.h3__q99j7,
                        projectcss.__wab_text,
                        sty.h3___7Diq
                      )}
                    >
                      {"Program Kickoff - July 1st, 2024"}
                    </h3>
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.p__q99j7,
                        projectcss.__wab_text,
                        sty.p__xP82O
                      )}
                    >
                      {
                        "Arrival in Silicon Valley, orientation week, housing setup, and introduction to mentors and fellow participants."
                      }
                    </p>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__bMsuX)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.h3__q99j7,
                        projectcss.__wab_text,
                        sty.h3__rbDm4
                      )}
                    >
                      {"Intensive Program - July - August 2024"}
                    </h3>
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.p__q99j7,
                        projectcss.__wab_text,
                        sty.p__jgoxK
                      )}
                    >
                      {
                        "6 weeks of workshops, mentorship sessions, company visits, networking events, and project development."
                      }
                    </p>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__wq2Kf)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.h3__q99j7,
                        projectcss.__wab_text,
                        sty.h3__rLRg5
                      )}
                    >
                      {"Demo Day - August 30th, 2024"}
                    </h3>
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.p__q99j7,
                        projectcss.__wab_text,
                        sty.p___56F56
                      )}
                    >
                      {
                        "Present your projects to investors, entrepreneurs, and industry leaders. Celebrate your achievements and new connections."
                      }
                    </p>
                  </div>
                </div>
              </div>
            </section>
            <section className={classNames(projectcss.all, sty.section__qxZwo)}>
              <div className={classNames(projectcss.all, sty.freeBox___8H1P7)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.h2__q99j7,
                    projectcss.__wab_text,
                    sty.h2__fJJmx
                  )}
                >
                  {"Ready to Transform Your Future?"}
                </h2>
                <p
                  className={classNames(
                    projectcss.all,
                    projectcss.p,
                    projectcss.p__q99j7,
                    projectcss.__wab_text,
                    sty.p__wiHef
                  )}
                >
                  {
                    "Join the next generation of entrepreneurs in Silicon Valley. Applications close June 1st, 2024. Don't wait - your startup journey begins here."
                  }
                </p>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.a__q99j7,
                    sty.link__fUagt
                  )}
                  component={Link}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  <span
                    className={classNames(
                      projectcss.all,
                      projectcss.span,
                      projectcss.span__q99j7,
                      projectcss.__wab_text,
                      sty.span___2Dpm
                    )}
                  >
                    {"Apply Now - Deadline June 1st"}
                  </span>
                </PlasmicLink__>
              </div>
            </section>
            <footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames(projectcss.all, sty.footer)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__cTvs8)}>
                <div className={classNames(projectcss.all, sty.freeBox__mZiaa)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__woRsi)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.h3__q99j7,
                        projectcss.__wab_text,
                        sty.h3__hi4Mz
                      )}
                    >
                      {"Silkroad Fellowship"}
                    </h3>
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.p__q99j7,
                        projectcss.__wab_text,
                        sty.p__nyQly
                      )}
                    >
                      {
                        "Empowering the next generation of entrepreneurs through immersive Silicon Valley experience."
                      }
                    </p>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___60CKe)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.h3__q99j7,
                        projectcss.__wab_text,
                        sty.h3__hS2DD
                      )}
                    >
                      {"Program"}
                    </h3>
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.p__q99j7,
                        projectcss.__wab_text,
                        sty.p___19AiY
                      )}
                    >
                      {"Overview"}
                    </p>
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.p__q99j7,
                        projectcss.__wab_text,
                        sty.p___4Q2IF
                      )}
                    >
                      {"Benefits"}
                    </p>
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.p__q99j7,
                        projectcss.__wab_text,
                        sty.p__a2AjL
                      )}
                    >
                      {"Timeline"}
                    </p>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__eOvVp)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.h3__q99j7,
                        projectcss.__wab_text,
                        sty.h3__yIsXn
                      )}
                    >
                      {"Contact"}
                    </h3>
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.p__q99j7,
                        projectcss.__wab_text,
                        sty.p___71Bgk
                      )}
                    >
                      {"info@silkroadfellowship.com"}
                    </p>
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.p__q99j7,
                        projectcss.__wab_text,
                        sty.p__i0A
                      )}
                    >
                      {"+1 (555) 123-4567"}
                    </p>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__eh0F7)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.h3__q99j7,
                        projectcss.__wab_text,
                        sty.h3__fEv1X
                      )}
                    >
                      {"Follow Us"}
                    </h3>
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.p__q99j7,
                        projectcss.__wab_text,
                        sty.p__pM
                      )}
                    >
                      {"LinkedIn"}
                    </p>
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.p__q99j7,
                        projectcss.__wab_text,
                        sty.p__lba8O
                      )}
                    >
                      {"Twitter"}
                    </p>
                    <p
                      className={classNames(
                        projectcss.all,
                        projectcss.p,
                        projectcss.p__q99j7,
                        projectcss.__wab_text,
                        sty.p__y3Qiz
                      )}
                    >
                      {"Instagram"}
                    </p>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__wXhr7)}>
                  <p
                    className={classNames(
                      projectcss.all,
                      projectcss.p,
                      projectcss.p__q99j7,
                      projectcss.__wab_text,
                      sty.p__nGfr2
                    )}
                  >
                    {
                      "\u00a9 2024 Silkroad Fellowship Program. All rights reserved."
                    }
                  </p>
                </div>
              </div>
            </footer>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "nav", "h1", "footer"],
  nav: ["nav"],
  h1: ["h1"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  nav: "nav";
  h1: "h1";
  footer: "footer";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHome__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHome__VariantsArgs;
    args?: PlasmicHome__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHome__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHome__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHome__ArgProps,
          internalVariantPropNames: PlasmicHome__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    nav: makeNodeComponent("nav"),
    h1: makeNodeComponent("h1"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/",
      pagePath: "/",
      params: {},
      query: {}
    })
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
