/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: q99j7awHXXkWnTbGHfeoZt
// Component: Hn3uC4k439p5

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import IconLink from "../../IconLink"; // plasmic-import: HXQgQF2iOl0T/component
import TextInput from "../../TextInput"; // plasmic-import: imfkMeZlwEFG/component
import Button from "../../Button"; // plasmic-import: ltBp1iInfrQV/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: q99j7awHXXkWnTbGHfeoZt/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: q99j7awHXXkWnTbGHfeoZt/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: q99j7awHXXkWnTbGHfeoZt/projectcss
import sty from "./PlasmicFooter.module.css"; // plasmic-import: Hn3uC4k439p5/css

import LogoIcon from "./icons/PlasmicIcon__Logo"; // plasmic-import: XOPUZ2IrdgSY/icon
import SearchSvgIcon from "./icons/PlasmicIcon__SearchSvg"; // plasmic-import: uLJgMHa9Xd5S/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: 9wNu8lQOr9CS/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: cqVQ_NIxWLeo/icon
import TwitterIconIcon from "./icons/PlasmicIcon__TwitterIcon"; // plasmic-import: ikFk3EEb855w/icon
import GithubIconIcon from "./icons/PlasmicIcon__GithubIcon"; // plasmic-import: uH5UPcJ17bsr/icon
import FacebookIconIcon from "./icons/PlasmicIcon__FacebookIcon"; // plasmic-import: 7m_M823KTikH/icon

createPlasmicElementProxy;

export type PlasmicFooter__VariantMembers = {};
export type PlasmicFooter__VariantsArgs = {};
type VariantPropType = keyof PlasmicFooter__VariantsArgs;
export const PlasmicFooter__VariantProps = new Array<VariantPropType>();

export type PlasmicFooter__ArgsType = {};
type ArgPropType = keyof PlasmicFooter__ArgsType;
export const PlasmicFooter__ArgProps = new Array<ArgPropType>();

export type PlasmicFooter__OverridesType = {
  root?: Flex__<"div">;
  textInput?: Flex__<typeof TextInput>;
  button?: Flex__<typeof Button>;
};

export interface DefaultFooterProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFooter__RenderFunc(props: {
  variants: PlasmicFooter__VariantsArgs;
  args: PlasmicFooter__ArgsType;
  overrides: PlasmicFooter__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "textInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__wEt1L)} />

      <div className={classNames(projectcss.all, sty.freeBox__czklf)}>
        <div className={classNames(projectcss.all, sty.freeBox__zHcla)}>
          <IconLink
            className={classNames("__wab_instance", sty.iconLink__nzdfK)}
            icon={
              <LogoIcon
                className={classNames(projectcss.all, sty.svg__j6Nx6)}
                role={"img"}
              />
            }
          />

          <div className={classNames(projectcss.all, sty.freeBox__j4Zt)}>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.a__q99j7,
                projectcss.__wab_text,
                sty.link__r8JbP
              )}
              component={Link}
              href={"#"}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Terms"}
            </PlasmicLink__>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___0Ve6W
              )}
            >
              {" \u00b7 "}
            </div>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.a__q99j7,
                projectcss.__wab_text,
                sty.link__xv5Zu
              )}
              component={Link}
              href={"#"}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Privacy"}
            </PlasmicLink__>
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__lVnw8)}>
          <div className={classNames(projectcss.all, sty.freeBox__wxi4T)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__iDnWg
              )}
            >
              {"Products"}
            </div>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.a__q99j7,
                projectcss.__wab_text,
                sty.link___4GLvs
              )}
              component={Link}
              href={"#"}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Web Studio"}
            </PlasmicLink__>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.a__q99j7,
                projectcss.__wab_text,
                sty.link__ivDqm
              )}
              component={Link}
              href={"#"}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"DynamicBox Flex"}
            </PlasmicLink__>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.a__q99j7,
                projectcss.__wab_text,
                sty.link__c1KwE
              )}
              component={Link}
              href={"#"}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Programming Forms"}
            </PlasmicLink__>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.a__q99j7,
                projectcss.__wab_text,
                sty.link__efIy3
              )}
              component={Link}
              href={"#"}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Integrations"}
            </PlasmicLink__>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.a__q99j7,
                projectcss.__wab_text,
                sty.link__rSqGa
              )}
              component={Link}
              href={"#"}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Command-line"}
            </PlasmicLink__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__gNbw)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__n8Dmt
              )}
            >
              {"Resources"}
            </div>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.a__q99j7,
                projectcss.__wab_text,
                sty.link__vww5N
              )}
              component={Link}
              href={"#"}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Documentation"}
            </PlasmicLink__>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.a__q99j7,
                projectcss.__wab_text,
                sty.link__ie3D0
              )}
              component={Link}
              href={"#"}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Tutorials & Guides"}
            </PlasmicLink__>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.a__q99j7,
                projectcss.__wab_text,
                sty.link__eKqtp
              )}
              component={Link}
              href={"#"}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Blog"}
            </PlasmicLink__>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.a__q99j7,
                projectcss.__wab_text,
                sty.link__k0Vu
              )}
              component={Link}
              href={"#"}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Support Center"}
            </PlasmicLink__>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.a__q99j7,
                projectcss.__wab_text,
                sty.link__cxNr6
              )}
              component={Link}
              href={"#"}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Partners"}
            </PlasmicLink__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__wDru5)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ldKsl
              )}
            >
              {"Company"}
            </div>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.a__q99j7,
                projectcss.__wab_text,
                sty.link__iiwhB
              )}
              component={Link}
              href={"#"}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Home"}
            </PlasmicLink__>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.a__q99j7,
                projectcss.__wab_text,
                sty.link__j4Lkg
              )}
              component={Link}
              href={"#"}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"About us"}
            </PlasmicLink__>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.a__q99j7,
                projectcss.__wab_text,
                sty.link__bTHnh
              )}
              component={Link}
              href={"#"}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Company values"}
            </PlasmicLink__>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.a__q99j7,
                projectcss.__wab_text,
                sty.link__sKaX
              )}
              component={Link}
              href={"#"}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Pricing"}
            </PlasmicLink__>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.a__q99j7,
                projectcss.__wab_text,
                sty.link__aWs8L
              )}
              component={Link}
              href={"#"}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Privacy policy"}
            </PlasmicLink__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__tjY8V)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__aRur1
              )}
            >
              {"Subscribe"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__fat4O
              )}
            >
              {"Get the latest news and articles to your inbox every month."}
            </div>
            <TextInput
              data-plasmic-name={"textInput"}
              data-plasmic-override={overrides.textInput}
              className={classNames("__wab_instance", sty.textInput)}
              endIcon={
                <Button
                  data-plasmic-name={"button"}
                  data-plasmic-override={overrides.button}
                  className={classNames("__wab_instance", sty.button)}
                  color={"clear"}
                  size={"compact"}
                  startIcon={
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg__fufSs)}
                      role={"img"}
                    />
                  }
                  submitsForm={true}
                >
                  <IconIcon
                    className={classNames(projectcss.all, sty.svg___1C9HT)}
                    role={"img"}
                  />
                </Button>
              }
              fontSize={"small"}
              onChange={async (...eventArgs: any) => {
                ((...eventArgs) => {
                  generateStateOnChangeProp($state, ["textInput", "value"])(
                    (e => e.target?.value).apply(null, eventArgs)
                  );
                }).apply(null, eventArgs);

                if (
                  eventArgs.length > 1 &&
                  eventArgs[1] &&
                  eventArgs[1]._plasmic_state_init_
                ) {
                  return;
                }
              }}
              placeholder={"Your email"}
              showEndIcon={true}
              value={
                generateStateValueProp($state, ["textInput", "value"]) ?? ""
              }
            />
          </div>
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__gxLqN)} />

      <div className={classNames(projectcss.all, sty.freeBox___6W0Et)}>
        <div className={classNames(projectcss.all, sty.freeBox___5Wabi)}>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.a__q99j7,
              projectcss.__wab_text,
              sty.link__grdjr
            )}
            component={Link}
            href={"https://cruip.com/"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Designed by Cruip. "}
          </PlasmicLink__>
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.a__q99j7,
              projectcss.__wab_text,
              sty.link__ms0Mk
            )}
            component={Link}
            href={"https://www.plasmic.app/"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            {"Built in Plasmic. "}
          </PlasmicLink__>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___8Q76I
            )}
          >
            {"All rights reserved."}
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__whMqw)}>
          <IconLink
            className={classNames("__wab_instance", sty.iconLink___40Pag)}
            icon={
              <TwitterIconIcon
                className={classNames(projectcss.all, sty.svg___1Y3H)}
                role={"img"}
              />
            }
          />

          <IconLink
            className={classNames("__wab_instance", sty.iconLink__aQlBn)}
            icon={
              <GithubIconIcon
                className={classNames(projectcss.all, sty.svg__sUt52)}
                role={"img"}
              />
            }
          />

          <IconLink
            className={classNames("__wab_instance", sty.iconLink__bEuOa)}
            icon={
              <FacebookIconIcon
                className={classNames(projectcss.all, sty.svg__pUuK2)}
                role={"img"}
              />
            }
          />
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "textInput", "button"],
  textInput: ["textInput", "button"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  textInput: typeof TextInput;
  button: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFooter__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFooter__VariantsArgs;
    args?: PlasmicFooter__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicFooter__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicFooter__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFooter__ArgProps,
          internalVariantPropNames: PlasmicFooter__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFooter__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooter";
  } else {
    func.displayName = `PlasmicFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicFooter = Object.assign(
  // Top-level PlasmicFooter renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    textInput: makeNodeComponent("textInput"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicFooter
    internalVariantProps: PlasmicFooter__VariantProps,
    internalArgProps: PlasmicFooter__ArgProps
  }
);

export default PlasmicFooter;
/* prettier-ignore-end */
